# Generated by Django 4.1 on 2024-06-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ACE_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first", models.CharField(max_length=128)),
                ("last", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=264, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="topic",
            name="top_name",
            field=models.CharField(max_length=264),
        ),
    ]
